apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: estephe-app
spec:
  destination:
    name: ''
    namespace: estephe
    server: https://kubernetes.default.svc
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
