apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
      app: httpd
spec:
  selector:
    app: httpd
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
