apiVersion: v1
kind: Service
metadata:
  name: myapp-service1
  namespace: argocd
  labels:
      app: myapp1
spec:
  selector:
    app: myapp1
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
